### PR TITLE
Fix a bug in permissive map

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This fixes a bug in the permissive map that I found when migrating `FusionReduceImplicitBroadcast3_CUDA` from trivial reduction to squeeze.

In short, the bug is, in the following fusion
```
T0[I*b]
T1[I] = squeeze(T0, {false, true})
```
`I*b` and `I` are not mapped in the permissive map.

I fixed this bug by using the "symmetric" API of `BestEffortReplay`, and this fix would also provide a more fundamental fix for the upstream issue https://github.com/pytorch/pytorch/issues/84510 and removes the workaround from Shiming introduced in https://github.com/csarofeen/pytorch/pull/1960.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp [hunk 1]
```diff
@@ -6599,21 +6598,21 @@ TEST_F(NVFuserTest, FusionRepro2094_CUDA) {
   {
     auto tv0 = TensorViewBuilder()
                    .ndims(1)
-                   .shape({-1})
```
Comment (zasdfgbnm) [inline torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp]: This is not related to this PR, but @xwang233 reported that this line is causing compilation error on our nightly CI. I can not reproduce it locally, but this is my guessing fix.

File: torch/csrc/jit/codegen/cuda/lower_shift.cpp [hunk 2]
```diff
@@ -638,7 +638,11 @@ bool extentCompare(
     Cmp cmp,
     const DisjointSets<IterDomain*>& permissive_map) {
   TORCH_INTERNAL_ASSERT(
-      permissive_map.strictAreMapped(id1, id2), "Invalid axes to compare");
+      permissive_map.strictAreMapped(id1, id2),
```
Comment (zasdfgbnm) [inline torch/csrc/jit/codegen/cuda/lower_shift.cpp:641]: This is the failing point in `FusionReduceImplicitBroadcast3_CUDA`

File: torch/csrc/jit/codegen/cuda/lower_index_compute.cpp [hunk 3]
```diff
@@ -731,36 +731,8 @@ void LoopIndexingAnalysis::constructLoopDomains() {
...
-              //  loop "locally", i.e. only with and with only the iterdomains
-              //  on the
-              //
-              //  given consumer tv.
-              //  When we cannot find an exact mapping, the permissive mapping
-              //  would
-              //   help defering the indexing resolution for this loop nest
-              //   level to other iterdomain expressions from tv's that are
-              //   further concretized and usually they are further down the
-              //   consumer chain of the given consumer tv.
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_index_compute.cpp]: This part still seems relevant, so please keep it in the code

Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/lower_index_compute.cpp]: added

**Comment by naoyam** [comment]
Just a quick clarification, does the bug you're referring to only happen with the new squeeze interface? Or does it also matter for trivial reductions as well?

**Comment by zasdfgbnm** [comment]
> Just a quick clarification, does the bug you're referring to only happen with the new squeeze interface? Or does it also matter for trivial reductions as well?

It does matter for trivial reduction as well. But since for trivial reduction, the ID is removed one step later, the problem could hide deeper and would be harder to trigger. I made a fix for trivial reduction for loop mapping in the past: https://github.com/csarofeen/pytorch/pull/1871, but that fix was not as complete as this one.

**Comment by naoyam** [comment]
Edit: I should first mention: This is really a nice catch, Xiang!

It seems that the root cause of the issue is BestEffortReplay does not map forwarded IDs:

https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/transform_iter.cpp#L381

I wonder if we should actually not remove the mapping. Does keeping the mapping also fix the issue? I suspect so, though I'm not sure what other side effects could exist.

I think the question is what `BestEffortReplay::getReplay()` should return. Basically this PR fixes the issue by not using it but `BestEffortReplay::getDisjointSets()`, and I think the subtle difference between these two is confusing.

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp [hunk 4]
```diff
@@ -12,7 +12,8 @@ bool DomainMap::areAllInputIdsMappedTo(TensorView* input_tv, TensorView* tv)
   // Get concrete IDs for input root or rfactor domain
   std::unordered_set<IterDomain*> in_concrete_ids;
   for (auto in_id : input_tv->getMaybeRFactorDomain()) {
-    auto concrete = ca_map_.getConcreteMappedID(in_id, IdMappingMode::EXACT);
+    auto concrete =
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp:17]: Is this related to the permissive map change? Don't remember what this function is trying to do, but why using the permissive map instead of the exact map?

**Comment by zasdfgbnm** [comment]
Oh sorry @naoyam. I clicked the wrong button, and edited your comment instead of replying to it.... I will try to recover.

**Comment by zasdfgbnm** [comment]
> I think the question is what `BestEffortReplay::getReplay()` should return. Basically this PR fixes the issue by not using it but `BestEffortReplay::getDisjointSets()`, and I think the subtle difference between these two is confusing.

I have a feeling that `getReplay` should return a `std::unordered_map<IterDomain*, std::vector<IterDomain*>>`. For the example of
```
T0[I*b*b]
T1[I]
```
it should return `I -> {I, I*b, I*b*b}`.

**Comment by naoyam** [comment]
> > I think the question is what `BestEffortReplay::getReplay()` should return. Basically this PR fixes the issue by not using it but `BestEffortReplay::getDisjointSets()`, and I think the subtle difference between these two is confusing.
> 
> I have a feeling that `getReplay` should return a `std::unordered_map<IterDomain*, std::vector<IterDomain*>>`. For the example of
> 
> ```
> T0[I*b*b]
> T1[I]
> ```
> 
> it should return `I -> {I, I*b, I*b*b}`.

So, you're saying we should keep the forwarded mapping, right? I thought that's what `BestEffortReplay` does, but apparently my memory was wrong.

**Comment by zasdfgbnm** [comment]
> So, you're saying we should keep the forwarded mapping, right? I thought that's what `BestEffortReplay` does, but apparently my memory was wrong.

I think there are two issues here: For
```
T0[I*b*b]
T1[I] = squeeze(T0)
```

**Question 1:**
What should we have in the P->C replay? Should we have just `I*b*b->I`, or do we need:
```
I->I
I*b->I
I*b*b->I
```

**Question 2:**
What should we have in the C->P replay? Should we have  `I->I` or `I->I*b*b`, or do we need:
```
I->{I, I*b, I*b*b}
```

I think you were talking about question 1, and I was talking about question 2. And broadcasting is the symmetry of squeeze and trivial reduction. A problem in P2C replay in broadcast will occur in a C2P replay in squeeze/trivial reduction, and vice versa.

**Comment by zasdfgbnm** [comment]
Combining question 1 and question 2, and for the following example with trivial reduction and broadcast
```
T0[I*r*r]
T1[I*b*b] = broadcast(T0)
```
should we have
```
I->{I, I*r, I*r*r}
I*b->{I, I*r, I*r*r}
I*b*b->{I, I*r, I*r*r}
```

**Comment by naoyam** [comment]
> > So, you're saying we should keep the forwarded mapping, right? I thought that's what `BestEffortReplay` does, but apparently my memory was wrong.
> 
> I think there are two issues here: For
> 
> ```
> T0[I*b*b]
> T1[I] = squeeze(T0)
> ```
> 
> **Question 1:** What should we have in the P->C replay? Should we have just `I*b*b->I`, or do we need:
> 
> ```
> I->I
> I*b->I
> I*b*b->I
> ```
> 

Assuming `T0` is `T0[(I*b)*b]`, then yes I'd expect the permissive map should map them all.

> **Question 2:** What should we have in the C->P replay? Should we have `I->I` or `I->I*b*b`, or do we need:
> 
> ```
> I->{I, I*b, I*b*b}
> ```
> 
> I think you were talking about question 1, and I was talking about question 2. And broadcasting is the symmetry of squeeze and trivial reduction. A problem in P2C replay in broadcast will occur in a C2P replay in squeeze/trivial reduction, and vice versa.

Similarly, yes, the C2P map should map `I` to all the three IDs.

**Comment by zasdfgbnm** [comment]
If my memory is correct, the current behavior is: For question 1, we only have `I*b*b->I` and for question 2, we only have `I->I`. And this is the root cause of https://github.com/csarofeen/pytorch/pull/1871 because we are mapping some non-leaf domain in the loop mapping...

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp (hunk 4 above)
Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp:17]: Exact mapping is sufficient for the pointwise scheduler, but permissive mapping is required to allow the transpose scheduler to analyze fusions like
```
T0[I0, b] + T1[b, I1]
```
We are already using permissive map in the `eraseIfMapped` below, and it is wrong if we don't keep it consistent here.

However, this bug was not discovered until today, because my change makes the permissive map and exact map selecting a different concrete domain.

**Comment by naoyam** [comment]
I looked around where `BestEffortReplay` is used, and it seems we want to keep the final mappings only when it's used in `TransformReplay::replayPasC/replayCasP`, but for `ComputeAtMap::build`, we want have the mappings for the forwarded IDs. I may be missing some other usage, but basically these two are the only usages with the forwarding enabled. 

It seems to me this is just an interface design problem. It should be clear that some API only returns final mappings without forwarded IDs and some other API includes forwarded IDs as well. Currently, `getReplay` is the former, and `getDisjointSets` is the latter, which I don't think convey the slight difference of the interface. 

IMO, the behavior of `getReplay` makes sense. This is after all "best effort", so it seems to makes sense that it returns whatever the final mappings two tensors can be advanced without conflicts. On the other hard, the naming of `getDisjointSets` isn't clear to me. I don't have a good alternative name, but at least we should have a comment to describe the difference.

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp (hunk 4 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp:17]: I was wondering what potential side effects could be by changing it to use the permissive map, but if I understand the logic here correctly, we are only looking at root domains and broadcasts are immediately ignored anyway, so the only impact this change could have is the transpose case as you mentioned. Am I right?

**Comment by zasdfgbnm** [comment]
Is `getIterDomainEquivalence` a good name? That method effectively just gets the equivalence, as defined by forwarding and replay, of IDs.

**Comment by naoyam** [comment]
Yeah, that's better than `getDisjointSets` for sure.

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp (hunk 4 above)
Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp:17]: Yes

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp:17]: Can you please leave a comment about this?

**Comment by zasdfgbnm** [comment]
I have renamed it and added comments

**Review by naoyam — APPROVED** [review]
LGTM. Thanks for answering my questions. 

There might be a lot of conflicts with the `torchbenchPerf` branch.
